name: ios build and archive

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_deploy:
    runs-on: macos-12
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/.packages
            ${{ github.workspace }}/.flutter-plugins
            ${{ github.workspace }}/.flutter-plugin-dependencies
            ${{ github.workspace }}/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles(format('{0}{1}', github.workspace, '/pubspec.lock')) }}
          restore-keys: |
            build-pubspec-
      
      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-bundler-
      
      - name: cache pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}
      
      - name: setup fastlane
        run: bundle install
      
      - name: fastlane match
        run: |
          export MATCH_GIT_BASIC_AUTHORIZATION=$(echo -n "$MATCH_GITHUB_USER:$MATCH_GITHUB_TOKEN" | base64)
          bundle exec fastlane custom_lane
        working-directory: ./ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GITHUB_USER: ${{ secrets.MATCH_GITHUB_USER }}
          MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      - name: build ipa
        run: flutter build ipa --release
